{{- if .Values.nginx.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intranet-search.fullname" . }}-nginx-config
  labels:
    {{- include "intranet-search.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Values.nginx.config | indent 4 }}
{{- end }}
