{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intranet-search.fullname" . }}-secrets
  labels:
    {{- include "intranet-search.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.elasticsearchApiKey }}
  elasticsearch.apiKey: {{ .Values.secrets.elasticsearchApiKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.elasticsearchUsername }}
  elasticsearch.username: {{ .Values.secrets.elasticsearchUsername | b64enc }}
  {{- end }}
  {{- if .Values.secrets.elasticsearchPassword }}
  elasticsearch.password: {{ .Values.secrets.elasticsearchPassword | b64enc }}
  {{- end }}
{{- end }}
