apiVersion: v2
name: intranet-search
description: A Helm chart for intranet-search Angular application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - angular
  - search
  - intranet
maintainers:
  - name: DevOps Team
